### PR TITLE
Update, change max pin

### PR DESCRIPTION
**Pull request by Tobias-Fischer**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin, please rerender

**Comment by Tobias-Fischer** [comment]
@wolfv @traversaro does this max pin look right?

**Comment by wolfv** [comment]
Hmm I think the idea was to have a lower bound that's the build version but Max bound that's x. I think there is also something like min_pin=x.x

**Comment by wolfv** [comment]
To be honest I'm not entirely sure what the right arguments would be to achieve a pin like: >=6.6,<7.0.0a

While we could actually remove the <7 since that's in the package name for these

**Comment by Tobias-Fischer** [comment]
Ahh yes. I added the `min_pin`. The `max_pin` shouldn't hurt so I suppose we can keep it?

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin, please rerender

**Comment by Tobias-Fischer** [comment]
This is ready to be merged @conda-forge/libignition-fuel-tools

**Comment by traversaro** [comment]
Thanks @Tobias-Fischer , I have one additional doubts.
 There is just something I do not get: why if we have: 
~~~
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}
~~~
this gets rendered as `>=1.11.2,<1.12` (see https://docs.conda.io/projects/conda-build/en/latest/resources/variants.html#pinning-expressions), why don't we get do simply something like:
~~~
  run_exports:
    - {{ pin_subpackage(name, max_pin='x') }}
~~~
that (I guess) should be rendered as `>=1.11.2,< 2.0` ?

Furthermore, if we use `min_pin` I think we should specify `x.x.x`, as new symbols can get introduced also in patch releases, so if something has been compiled with a igniton dependency version 1.11.2, we do not know if it will work with `1.11.0` .

**Comment by Tobias-Fischer** [comment]
Hmm I see. I updated the `min_pin` to include the patch level. Better be explicit than implicit @traversaro?

**Comment by traversaro** [comment]
> Hmm I see. I updated the `min_pin` to include the patch level. Better be explicit than implicit @traversaro?

Thanks! To be honest I was not sure in which way the previous one was rendered, but the new one I think it is quite clear.

**Comment by Tobias-Fischer** [comment]
Are you happy with the pins too, @wolfv? In this case I'll open similar PRs for the other ignition feedstocks.

**Comment by Tobias-Fischer** [comment]
Just found this:

> min_pin is implicitly 'x.x.x.x.x.x' and only needs to be set when it is beneficial to make it less specific. max_pin is the opposite. It defaults to 'x' and only needs to be set when it is beneficial to make it more specific.

(from @msarahan in https://github.com/conda-forge/conda-forge-pinning-feedstock/issues/4)

So I'll remove the explicit min_pin, and merge afterward.

**Pull request merged**
