### PR TITLE
Add https://github.com/ignitionrobotics/ign-fuel-tools/pull/178

### PR DESCRIPTION
**Pull request by Tobias-Fischer**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
Fix https://github.com/conda-forge/gazebo-feedstock/issues/76

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin, please rerender

**Review by traversaro — APPROVED** [review]

**Comment by Tobias-Fischer** [comment]
Unfortunately the patch doesn't apply cleanly. Do you think we can ask for a new release @traversaro? This would make it easy.

**Comment by traversaro** [comment]
> Unfortunately the patch doesn't apply cleanly. Do you think we can ask for a new release @traversaro? This would make it easy.

Done in https://github.com/ignitionrobotics/ign-fuel-tools/issues/189 . Something we can do in the meanwhile is to check if we need to update the ign-common3 releases that contain some related fixes, that probably are not automatically tracked by the bot not being the latest major release.

**Comment by Tobias-Fischer** [comment]
See #35 instead.

**Pull request closed without merging**
